name: Build .NET Project

on:
    push:
        branches:
            - main
            - master
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 10.0.x

            - name: Build solution
              run: dotnet publish --configuration Release
